/** @type {import('tailwindcss').Config} */
// Design tokens lifted verbatim from the Google Stitch "WildWatch Naturalist"
// export so the React components can use the exact same class names.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#224b33',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#424842',
        'surface-container-highest': '#e5e2de',
        'on-primary-container': '#97b99e',
        'tertiary-fixed-dim': '#a4d1b1',
        'dark-asset': '#20261F',
        error: '#ba1a1a',
        'fox-orange': '#C1572A',
        'text-secondary': '#6B6560',
        'on-tertiary': '#ffffff',
        'green-faint': '#EAF0EC',
        'on-secondary-container': '#764800',
        'on-error-container': '#93000a',
        secondary: '#855303',
        'primary-fixed-dim': '#adcfb3',
        'error-container': '#ffdad6',
        'secondary-fixed': '#ffddb9',
        'primary-fixed': '#c8ebce',
        outline: '#727972',
        'outline-variant': '#c2c8c0',
        'surface-dim': '#dcdad6',
        'surface-container-low': '#f6f3ef',
        'surface-container-high': '#ebe8e4',
        'surface-container-lowest': '#ffffff',
        'bear-brown': '#4A3728',
        border: '#E0DBD5',
        'on-surface': '#1c1c1a',
        'inverse-on-surface': '#f3f0ec',
        'on-tertiary-fixed': '#002110',
        'surface-bright': '#fcf9f5',
        tertiary: '#08341e',
        'secondary-container': '#fdb966',
        'surface-tint': '#46654f',
        background: '#F5F2EE',
        'on-secondary-fixed-variant': '#663e00',
        'amber-faint': '#FDF3E3',
        'primary-container': '#2c4a35',
        'on-primary-fixed': '#03210f',
        'on-background': '#1c1c1a',
        'on-secondary-fixed': '#2b1700',
        'on-tertiary-container': '#8eba9b',
        surface: '#FDFAF7',
        primary: '#153320',
        'turkey-sage': '#6B8E5E',
        'on-primary-fixed-variant': '#2f4d38',
        'deer-amber': '#C4883A',
        'on-primary': '#ffffff',
        'inverse-surface': '#31302e',
        'coyote-tan': '#8B7355',
        'gray-fox': '#7A7A7A',
        'surface-container': '#f0edea',
        'secondary-fixed-dim': '#fdb966',
        'on-error': '#ffffff',
        'inverse-primary': '#adcfb3',
        'surface-variant': '#e5e2de',
        'tertiary-fixed': '#bfedcc',
        'on-tertiary-fixed-variant': '#264f36',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'internal-stack': '10px',
        'page-margin-desktop': '32px',
        'gutter-grid': '16px',
        'gutter-photo': '14px',
        'tight-gap': '8px',
        'base-unit': '4px',
        'page-margin-mobile': '16px',
        'component-gap': '12px',
      },
      fontFamily: {
        'headline-lg-mobile': ['DM Serif Display', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['DM Serif Display', 'serif'],
        'button-text': ['Inter', 'sans-serif'],
        'nav-link': ['Inter', 'sans-serif'],
        'headline-lg': ['DM Serif Display', 'serif'],
        'micro-tag': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg-mobile': ['26px', { lineHeight: '1.2', fontWeight: '400' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '1.3', fontWeight: '400' }],
        'button-text': ['13px', { lineHeight: '16px', fontWeight: '500' }],
        'nav-link': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '400' }],
        'micro-tag': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
}
